---
- name: Build an image with the shell module for a remote docker host
  hosts: ceros-ski

  tasks:
    - name: Download ceros ski project
      shell: rm -rf /ceros-challenge && mkdir /ceros-challenge && git clone https://16be005cfa58272196251b2974be185d823ca04a@github.com/carloseaf/ceros-challenge.git /ceros-challenge

    - name: Ceros Ski build
      shell: docker build -t ceros-ski-web /ceros-challenge/ceros-ski

    - name: Remove ceros-ski-web-1
      shell: docker rm -f ceros-ski-web-1

    - name: Deploy ceros-ski-web [1]
      shell: docker run --name ceros-ski-web-1 --restart=always -itd ceros-ski-web

    - name: Remove ceros-ski-web-2
      shell: docker rm -f ceros-ski-web-2

    - name: Deploy ceros-ski-web [2]
      shell: docker run --name ceros-ski-web-2 --restart=always -itd ceros-ski-web
